# docker-compose.yml
services:
    app:
        container_name: cuba_admin
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        volumes:
            - .:/var/www/html
        networks:
            - cuba_admin
            - shared-network

    nginx:
        image: nginx:1.20
        container_name: cuba_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - cuba_admin
            - shared-network

networks:
    cuba_admin:
        driver: bridge
    shared-network:
        external: true
